export const OPEN_MAINTAIN_CAR_CARD_MODAL = 'open_maintain_car_card_modal'
export const CLOSE_MAINTAIN_CAR_CARD_MODAL_OK = 'close_maintain_car_card_modal_ok'
export const CLOSE_MAINTAIN_CAR_CARD_MODAL_CANCEL = 'close_maintain_car_card_modal_cancel'
export const CHANGE_MAINTAIN_CAR_CARD_MODAL_INPUT_VALUE = 'change_maintain_car_card_modal_input_value'