module.exports = (sequelize, Sequelize) => {
    const Label = sequelize.define('Label', {
        id: {
            type: Sequelize.INTEGER,
            autoIncrement: true,
            allowNull: false,
            primaryKey: true
        },
        labelName: {
          type: Sequelize.STRING,
          allowNull: false,
          unique: true
        },
        createdAt: {
            field: 'created_at',
            type: Sequelize.DATE,
            allowNull: false,
            defaultValue: Sequelize.NOW
        },
        updatedAt: {
            field: 'updated_at',
            type: Sequelize.DATE,
            allowNull: false,
            defaultValue: Sequelize.NOW
        },
    }, {
        timestamps: true,
        paranoid: true
    });

    Label.bulkCreate([
        { labelName: "person" },
        { labelName: "bicycle" },
        { labelName: "car" },
        { labelName: "motorcycle" },
        { labelName: "airplane" },
        { labelName: "bus" },
        { labelName: "train" },
        { labelName: "truck" },
        { labelName: "boat" },
        { labelName: "traffic light" },
        { labelName: "fire hydrant" },
        { labelName: "stop sign" },
        { labelName: "parking meter" },
        { labelName: "bench" },
        { labelName: "bird" },
        { labelName: "cat" },
        { labelName: "dog" },
        { labelName: "horse" },
        { labelName: "sheep" },
        { labelName: "cow" },
        { labelName: "elephant" },
        { labelName: "bear" },
        { labelName: "zebra" },
        { labelName: "giraffe" },
        { labelName: "backpack" },
        { labelName: "umbrella" },
        { labelName: "handbag" },
        { labelName: "tie" },
        { labelName: "suitcase" },
        { labelName: "frisbee" },
        { labelName: "skis" },
        { labelName: "snowboard" },
        { labelName: "sports ball" },
        { labelName: "kite" },
        { labelName: "baseball bat" },
        { labelName: "baseball glove" },
        { labelName: "skateboard" },
        { labelName: "surfboard" },
        { labelName: "tennis racket" },
        { labelName: "bottle" },
        { labelName: "wine glass" },
        { labelName: "cup" },
        { labelName: "fork" },
        { labelName: "knife" },
        { labelName: "spoon" },
        { labelName: "bowl" },
        { labelName: "banana" },
        { labelName: "apple" },
        { labelName: "sandwich" },
        { labelName: "orange" },
        { labelName: "broccoli" },
        { labelName: "carrot" },
        { labelName: "hot dog" },
        { labelName: "pizza" },
        { labelName: "donut" },
        { labelName: "cake" },
        { labelName: "chair" },
        { labelName: "couch" },
        { labelName: "potted plant" },
        { labelName: "bed" },
        { labelName: "dining table" },
        { labelName: "toilet" },
        { labelName: "tv" },
        { labelName: "laptop" },
        { labelName: "mouse" },
        { labelName: "remote" },
        { labelName: "keyboard" },
        { labelName: "cell phone" },
        { labelName: "microwave" },
        { labelName: "oven" },
        { labelName: "toaster" },
        { labelName: "sink" },
        { labelName: "refrigerator" },
        { labelName: "book" },
        { labelName: "clock" },
        { labelName: "vase" },
        { labelName: "scissors" },
        { labelName: "teddy bear" },
        { labelName: "hair drier" },
        { labelName: "toothbrush" },
    ], { ignoreDuplicates: true });

    return Label;
};